name: Deploy NestJS to Coolify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test --if-present

      - name: Build project
        run: npm run build

      - name: Trigger Coolify Deploy
        run: |
          curl -X POST "${{ secrets.COOLIFY_API_URL }}/deploy" \
          -H "Authorization: Bearer ${{ secrets.COOLIFY_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{"id":"${{ secrets.COOLIFY_APP_ID }}"}'
